---

base_systemd_prefix: /etc/systemd
base_systemd_system: "{{ base_systemd_prefix }}/system"
base_systemd_network: "{{ base_systemd_prefix }}/network"
base_local_folder: /usr/local

base_debian_repository: https://deb.debian.org/debian
base_debian_security: https://deb.debian.org/debian-security

base_ntp_servers: ntp1.inrim.it ntp2.inrim.it time.euro.apple.com time.asia.apple.com time.apple.com
base_ntp_fallback: time.cloudflare.com ntp1.fortiguard.com ntp2.fortiguard.com ntp.checkpoint.com ntp2.checkpoint.com

base_ssh_casignaturealgorithms:
  - ecdsa-sha2-nistp521
  - ssh-ed25519
base_ssh_ciphers:
  - aes256-gcm@openssh.com
  - chacha20-poly1305@openssh.com
base_ssh_hostkeyalgorithms:
  - ssh-ed25519-cert-v01@openssh.com
  - ecdsa-sha2-nistp521-cert-v01@openssh.com
  - ecdsa-sha2-nistp521
  - ssh-ed25519
base_ssh_kexalgorithms:
  - sntrup761x25519-sha512@openssh.com
  - sntrup761x25519-sha512
  - ecdh-sha2-nistp521
  - diffie-hellman-group-exchange-sha256
  - diffie-hellman-group18-sha512
  - diffie-hellman-group14-sha256
  - curve25519-sha256@libssh.org
  - curve25519-sha256
base_ssh_macs:
  - umac-128-etm@openssh.com
  - hmac-sha2-512-etm@openssh.com
  - umac-128@openssh.com
  - hmac-sha2-512

base_postgresql_socketdir: /var/run/postgresql/
base_postgresql_version: 17
base_postgresql_socketuser: postgres
base_prometheus_postgres_exporter: postgres_exporter

base_resolve_ipv6: "2606:4700:4700::1112#security.cloudflare-dns.com 2606:4700:4700::1002#security.cloudflare-dns.com"
base_resolve_ipv4: "1.1.1.2#security.cloudflare-dns.com 1.0.0.2#security.cloudflare-dns.com"

base_k0s_version: "v1.34.3+k0s.0"
base_k0s_config_path: /etc/k0s/k0s.yaml
base_k0s_datastore_endpoint: "postgres://kine:kine@localhost:5432/kine?sslmode=disable"
base_k0s_binary_path: "{{ base_local_folder }}/bin/k0s"
